analysis_type: time_of_day
version: 1.0.0
model_configuration:
  model: qwen2.5vl:32b
  temperature: 0.1
  top_p: 0.9
  top_k: 40
  num_ctx: 32768
vision_optimization:
  max_edge_pixels: 1344
  preserve_aspect_ratio: true
parallel_processing:
  max_concurrency: 8
  worker_count: 8
  batch_size: 1
  timeout_seconds: 60
prompts:
  system_prompt: '# system prompt for time_of_day analysis (externalized)

    '
  user_prompt: '# user prompt template for time_of_day analysis (externalized)

    '
validation_constraints:
  rules:
  - no meta-descriptive language
  - json output only
  output_format: json
  required_fields: []
  data_types: {}
performance_targets:
  throughput_target: 800+ per worker acceptable
  success_rate_target: 0.95
  max_latency_ms: 2000
  min_accuracy: 0.9
  throughput_goals:
  - '>= 800/worker sustained'
qa_stages:
- structural
- content_quality
- domain_expert
metadata:
  name: Time Of Day
  version: 1.0.0
  description: Configuration for time_of_day analysis
  analysis_type: time_of_day
