# GF-25 v3 Analysis Configuration Template [CONFIG-ARCH]
# Use this as a base for new analysis types. Do NOT place in configs/ root.
# Replace placeholders as needed.

metadata:
  name: "<analysis friendly name>"
  version: "1.0.0"
  description: "<short description of this analysis configuration>"
  analysis_type: "<one of: activities|ages|body_shapes|captions|category|colors|composition|emotions|ethnicity|events|gender|lighting|locations|objects|occlusions|outfits|relationships|scene_description|themes|time_of_day|weather>"

model_configuration:
  model: qwen2.5vl:32b
  temperature: 0.1
  top_p: 0.9
  top_k: 40
  num_ctx: 32768
  # Either set num_predict or use alias max_tokens
  # num_predict: 1024
  # max_tokens: 1024  # alias for num_predict

vision_optimization:
  max_edge_pixels: 1344
  preserve_aspect_ratio: true

parallel_processing:
  max_concurrency: 8
  worker_count: 8
  batch_size: 1
  timeout_seconds: 60

prompts:
  system_prompt: |
    # system prompt goes here (externalized, no hardcoding in code)
  user_prompt: |
    # user prompt template goes here

validation_constraints:
  rules:
    - no meta-descriptive language
    - json output only
  output_format: json
  required_fields: []
  data_types: {}

performance_targets:
  throughput_target: "800+ per worker acceptable"
  success_rate_target: 0.95
  max_latency_ms: 2000
  min_accuracy: 0.9
  throughput_goals:
    - ">= 800/worker sustained"

qa_stages:
  - structural
  - content_quality
  - domain_expert
